### ISSUE TITLE
Make it easy to use nixsap

### ISSUE THREAD

**Issue by 0xABAB** [zalora/nixsap#27]
I see some interesting features. Thanks for this initiative.

Please add a script at a stable location which patches configuration.nix on NixOS to include nixsap features (i.e. add the line you referred to, downloads this repository from git, etc.). 

Afterwards package this in NixOS, such that it becomes trivial to start using this.

**Comment by danbst** [comment]
For NixOS
```
    imports = [                                   
      (builtins.fetchTarball "https://github.com/zalora/nixsap/archive/master.tar.gz")                
      "${builtins.fetchTarball "https://github.com/nixos/nixops/archive/master.tar.gz"}/nix/keys.nix"
    ];                                            
```

**Comment by ip1981** [comment]
Yes, generally you import `<nixsap>` in your machine module, either prefetched (`<nixsap>`), e. g. as git submodule, or with `fetchTarball` or `fetchGit`.

Btw, you might want to switch over to https://github.com/ip1981/nixsap ;)

**Comment by ip1981** [comment]
I prefer prefetched (local) stuff, because github and anything else cloud-like can be down or gone ;)

**Comment by 0xABAB** [comment]
Cool, why is it separate from the main project, btw? Is it that you first want to play with some features or do you just don't like to play with the other kids? ;)

**Comment by ip1981** [comment]
I'm not working for Zalora any more.
